/**
 * JSON → Markdown Table converter
 * Manual builder. All processing is 100% client-side.
 */

export interface MarkdownOptions {
  includeTitle?: boolean
  maxCellLength?: number
}

/**
 * Flatten a nested object to a flat record with dot-notation keys
 */
function flattenForMD(obj: unknown, prefix = ''): Record<string, string> {
  const result: Record<string, string> = {}
  if (obj === null || obj === undefined) {
    result[prefix || 'value'] = 'null'
    return result
  }
  if (Array.isArray(obj)) {
    result[prefix || 'value'] = `[${(obj as unknown[]).map(v => JSON.stringify(v)).join(', ')}]`
    return result
  }
  if (typeof obj === 'object') {
    for (const [key, val] of Object.entries(obj as Record<string, unknown>)) {
      const fullKey = prefix ? `${prefix}.${key}` : key
      if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
        Object.assign(result, flattenForMD(val, fullKey))
      } else if (Array.isArray(val)) {
        result[fullKey] = `[${(val as unknown[]).map(v => JSON.stringify(v)).join(', ')}]`
      } else {
        result[fullKey] = val === null ? 'null' : String(val)
      }
    }
    return result
  }
  result[prefix || 'value'] = String(obj)
  return result
}

/**
 * Escape Markdown table cell content
 */
function escapeMDCell(value: string, maxLen: number): string {
  let v = value.replace(/\|/g, '\\|').replace(/\n/g, ' ').replace(/\r/g, '')
  if (v.length > maxLen) {
    v = v.slice(0, maxLen - 3) + '...'
  }
  return v
}

export function toMarkdown(data: unknown, options: MarkdownOptions = {}): string {
  const { includeTitle = true, maxCellLength = 100 } = options

  // Normalize to array of objects
  let rows: unknown[]
  if (Array.isArray(data)) {
    rows = data
  } else if (typeof data === 'object' && data !== null) {
    const vals = Object.values(data as Record<string, unknown>)
    if (vals.length === 1 && Array.isArray(vals[0])) {
      rows = vals[0] as unknown[]
    } else {
      rows = [data]
    }
  } else {
    rows = [{ value: data }]
  }

  if (rows.length === 0) return '*No data*'

  const flatRows = rows.map(r => flattenForMD(r))
  const allKeys = Array.from(new Set(flatRows.flatMap(r => Object.keys(r))))

  const lines: string[] = []

  if (includeTitle) {
    lines.push(`*Generated by Covalent · ${rows.length} row${rows.length !== 1 ? 's' : ''}*\n`)
  }

  // Header row
  lines.push(`| ${allKeys.map(k => escapeMDCell(k, maxCellLength)).join(' | ')} |`)

  // Separator row
  lines.push(`| ${allKeys.map(() => '---').join(' | ')} |`)

  // Data rows
  for (const row of flatRows) {
    const cells = allKeys.map(key => {
      const val = row[key] ?? ''
      return escapeMDCell(val, maxCellLength)
    })
    lines.push(`| ${cells.join(' | ')} |`)
  }

  return lines.join('\n')
}
