/**
 * JSON → SQL INSERT statements converter
 * Manual builder with proper escaping.
 * All processing is 100% client-side.
 */

export interface SQLOptions {
  tableName?: string
  dialect?: 'mysql' | 'postgresql' | 'sqlite'
  batchSize?: number
}

/**
 * Escape a value for safe SQL insertion
 */
function escapeSQLValue(value: unknown, dialect: string): string {
  if (value === null || value === undefined) return 'NULL'

  if (typeof value === 'boolean') {
    if (dialect === 'mysql') return value ? '1' : '0'
    return value ? 'TRUE' : 'FALSE'
  }

  if (typeof value === 'number') {
    if (!isFinite(value)) return 'NULL' // NaN, Infinity → NULL
    return String(value)
  }

  if (typeof value === 'object') {
    // Serialize objects/arrays as JSON strings
    const jsonStr = JSON.stringify(value)
    return `'${jsonStr.replace(/'/g, "''")}'`
  }

  // String — escape single quotes by doubling them
  const str = String(value)
  return `'${str.replace(/'/g, "''")}'`
}

/**
 * Quote an identifier (table/column name)
 */
function quoteIdentifier(name: string, dialect: string): string {
  if (dialect === 'mysql') return `\`${name.replace(/`/g, '``')}\``
  // PostgreSQL and SQLite use double quotes
  return `"${name.replace(/"/g, '""')}"`
}

/**
 * Flatten a row to primitive values (objects become JSON strings)
 */
function flattenRow(obj: unknown): Record<string, unknown> {
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) {
    return { value: obj }
  }
  const result: Record<string, unknown> = {}
  for (const [key, val] of Object.entries(obj as Record<string, unknown>)) {
    if (typeof val === 'object' && val !== null) {
      result[key] = JSON.stringify(val)
    } else {
      result[key] = val
    }
  }
  return result
}

export function toSQL(data: unknown, options: SQLOptions = {}): string {
  const { tableName = 'data', dialect = 'postgresql', batchSize = 50 } = options

  // Normalize to array
  let rows: unknown[]
  if (Array.isArray(data)) {
    rows = data
  } else if (typeof data === 'object' && data !== null) {
    const vals = Object.values(data as Record<string, unknown>)
    if (vals.length === 1 && Array.isArray(vals[0])) {
      rows = vals[0] as unknown[]
    } else {
      rows = [data]
    }
  } else {
    rows = [{ value: data }]
  }

  if (rows.length === 0) return `-- No data to insert into ${tableName}`

  const flatRows = rows.map(flattenRow)

  // Collect all unique keys
  const allKeys = Array.from(new Set(flatRows.flatMap(r => Object.keys(r))))

  const tableId = quoteIdentifier(tableName, dialect)
  const columnList = allKeys.map(k => quoteIdentifier(k, dialect)).join(', ')

  const lines: string[] = [
    `-- Generated by Covalent | ${new Date().toISOString()}`,
    `-- Dialect: ${dialect.toUpperCase()} | Rows: ${rows.length}`,
    '',
  ]

  // Generate INSERT statements in batches
  for (let i = 0; i < flatRows.length; i += batchSize) {
    const batch = flatRows.slice(i, i + batchSize)

    if (dialect === 'postgresql' || dialect === 'sqlite') {
      lines.push(`INSERT INTO ${tableId} (${columnList}) VALUES`)
      const valueLines = batch.map((row, idx) => {
        const vals = allKeys.map(key => escapeSQLValue(row[key] ?? null, dialect)).join(', ')
        const isLast = idx === batch.length - 1
        return `  (${vals})${isLast ? ';' : ','}`
      })
      lines.push(...valueLines)
    } else {
      // MySQL — separate statements per row
      for (const row of batch) {
        const vals = allKeys.map(key => escapeSQLValue(row[key] ?? null, dialect)).join(', ')
        lines.push(`INSERT INTO ${tableId} (${columnList}) VALUES (${vals});`)
      }
    }

    if (i + batchSize < flatRows.length) lines.push('')
  }

  return lines.join('\n')
}
